-- 2.	Для отслеживания действий с информацией о сотрудниках (добавление, изменение, удаление информации), создайте таблицу s_emp_log, хранящую:
-- •	информацию о времени выполнения действия,
-- •	информацию о типе действия,
-- •	данные до выполнения данного действия,
-- •	данные после  выполнения данного действия,
-- Напишите триггер, заносящий в s_emp_log данные о действиях с информацией о сотрудниках. 


CREATE TABLE s_emp_log (
  log_id      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  log_time    TIMESTAMP DEFAULT SYSTIMESTAMP,
  action_type VARCHAR2(10) CHECK (action_type IN ('INSERT','UPDATE','DELETE')),
  emp_id      NUMBER,                          -- ID сотрудника, с которым работали
  data_before VARCHAR2(4000),                  -- Данные ДО изменения
  data_after  VARCHAR2(4000)                   -- Данные ПОСЛЕ изменения
);


CREATE OR REPLACE TRIGGER trg_emp_audit
AFTER INSERT OR UPDATE OR DELETE ON s_emp
FOR EACH ROW
DECLARE
  v_before VARCHAR2(4000);
  v_after  VARCHAR2(4000);
BEGIN
  -- Формируем данные "до" (кроме INSERT)
  IF NOT INSERTING THEN
    v_before := 'ID='||:OLD.id||'|NAME='||:OLD.last_name||' '||:OLD.first_name||
                '|TITLE='||:OLD.title||'|DEPT='||:OLD.dept_id||
                '|SALARY='||NVL(TO_CHAR(:OLD.salary),'NULL')||
                '|COMM='||NVL(TO_CHAR(:OLD.commission_pct),'NULL');
  END IF;

  -- Формируем данные "после" (кроме DELETE)
  IF NOT DELETING THEN
    v_after := 'ID='||:NEW.id||'|NAME='||:NEW.last_name||' '||:NEW.first_name||
               '|TITLE='||:NEW.title||'|DEPT='||:NEW.dept_id||
               '|SALARY='||NVL(TO_CHAR(:NEW.salary),'NULL')||
               '|COMM='||NVL(TO_CHAR(:NEW.commission_pct),'NULL');
  END IF;

  -- Записываем в лог
  IF INSERTING THEN
    INSERT INTO s_emp_log (action_type, emp_id, data_before, data_after)
    VALUES ('INSERT', :NEW.id, NULL, v_after);
  ELSIF UPDATING THEN
    INSERT INTO s_emp_log (action_type, emp_id, data_before, data_after)
    VALUES ('UPDATE', :NEW.id, v_before, v_after);
  ELSIF DELETING THEN
    INSERT INTO s_emp_log (action_type, emp_id, data_before, data_after)
    VALUES ('DELETE', :OLD.id, v_before, NULL);
  END IF;
END;
/

-- Тесты 
INSERT INTO s_emp (id, last_name, first_name, userid, start_date, title, dept_id, salary, commission_pct)
VALUES (999, 'Testov', 'Ivan', 'itestov', SYSDATE, 'Tester', 31, 1500, 10);
COMMIT;

UPDATE s_emp SET salary = 1800 WHERE id = 999;
COMMIT;

DELETE FROM s_emp WHERE id = 999;
COMMIT;

-- Проверка лога
SELECT log_time, action_type, emp_id, 
       SUBSTR(data_before,1,80) AS before_short,
       SUBSTR(data_after,1,80) AS after_short
FROM s_emp_log ORDER BY log_time DESC;
