-- ============================================================
-- Часть 2: Система аудита (логирование с откатом)
-- Таблица для хранения истории изменений 3-х выбранных сущностей:
--   SELLERS, CUSTOMERS, SALES
-- Стиль: VARCHAR2(4000) с разделителем
-- ============================================================

PROMPT >>> Создание таблицы аудита...

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE audit_log CASCADE CONSTRAINTS PURGE';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE audit_log (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    table_name VARCHAR2(30) NOT NULL,
    operation VARCHAR2(10) NOT NULL CHECK (operation IN ('INSERT','UPDATE','DELETE')),
    op_timestamp TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    record_pk NUMBER NOT NULL,
    old_data VARCHAR2(4000),
    new_data VARCHAR2(4000),
    db_user VARCHAR2(30) DEFAULT USER
);

COMMENT ON TABLE audit_log IS 'Лог изменений по сущностям SELLERS, CUSTOMERS, SALES';
COMMENT ON COLUMN audit_log.table_name IS 'Название сущности (таблицы)';
COMMENT ON COLUMN audit_log.operation IS 'Тип операции: INSERT/UPDATE/DELETE';
COMMENT ON COLUMN audit_log.op_timestamp IS 'Дата и время операции';
COMMENT ON COLUMN audit_log.record_pk IS 'Первичный ключ изменённой записи';
COMMENT ON COLUMN audit_log.old_data IS 'Строка со старыми значениями (разделитель |)';
COMMENT ON COLUMN audit_log.new_data IS 'Строка с новыми значениями (разделитель |)';
COMMENT ON COLUMN audit_log.db_user IS 'Пользователь БД, выполнивший операцию';

PROMPT >>> Индексы для быстрого поиска по логу...

CREATE INDEX idx_audit_table ON audit_log(table_name);
CREATE INDEX idx_audit_operation ON audit_log(operation);
CREATE INDEX idx_audit_timestamp ON audit_log(op_timestamp);
CREATE INDEX idx_audit_record ON audit_log(record_pk);

PROMPT >>> Таблица аудита готова.
